Php8 compability
prooph/event-store-bus-bridge pull request #43
Opened 2021-03-29 21:33 UTC by fritz-gerneth

2021-03-31 09:22 UTC, fritz-gerneth commented
This should resolve once the `service-bus` dependency has been updated

2021-08-25 07:10 UTC, fritz-gerneth commented
@prolic you know if there is any way to rerun travis without a new commit?

2021-08-25 07:11 UTC, prolic commented
If you log in, there should be a button, at least there was one in the past.

On Wed, Aug 25, 2021, 03:10 Fritz Gerneth ***@***.***> wrote:

> @prolic <https://github.com/prolic> you know if there is any way to rerun
> travis without a new commit?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/prooph/event-store-bus-bridge/pull/43#issuecomment-905242437>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADAJPHQQXRCYVOK33N3DUDT6SJN3ANCNFSM42APALKA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-25 07:15 UTC, fritz-gerneth commented
Ah it is there, but disabled for me - I assume as this is not my repository. Can you trigger a re-test eventually?

2021-08-25 07:16 UTC, prolic commented
Sure, later today.

On Wed, Aug 25, 2021, 03:15 Fritz Gerneth ***@***.***> wrote:

> Ah it is there, but disabled for me - I assume as this is not my
> repository. Can you trigger a re-test eventually?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/prooph/event-store-bus-bridge/pull/43#issuecomment-905245493>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADAJPGPICNGRYY52TXYMOLT6SKATANCNFSM42APALKA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-25 17:11 UTC, prolic requested changes
Please update the year in LICENSE file as well.

2021-08-25 17:11 UTC, prolic commented on composer.json
>          "prooph/service-bus" : "^6.2",
require 6.3 now

2021-08-26 00:10 UTC, merged

2021-08-26 00:12 UTC, prolic commented
https://github.com/prooph/event-store-bus-bridge/releases/tag/v3.4.0